# NUMPY

In [1]:
import numpy as np

In [2]:
arr = np.array([23,4,57,89,20])

In [5]:
arr1 = np.array((23,4,57,89,20))

In [6]:
print(arr)

[23  4 57 89 20]


In [7]:
type(arr)

numpy.ndarray

In [10]:
arr.dtype

dtype('int32')

In [8]:
print(arr1)

[23  4 57 89 20]


In [9]:
type(arr1)

numpy.ndarray

In [11]:
arr1.dtype

dtype('int32')

In [12]:
# Assigning Data Type to each data structure

#  ==> arr = np.array([23, 46, 68, 80], dtype = "f")

## NUMPY PROPERTIES

### 1. dtype

In [13]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

arr1.dtype

dtype('int32')

In [14]:
arr2 = np.array((1, 2, 3,4, 5, 6), dtype = "f")

arr2.dtype

dtype('float32')

### 2. Dimensions => ndim()

###### Dimensions refer to the number of indices required to store a given no of arrays

In [22]:
arr = np.array([1, 2, 3])

print(arr.ndim)

print("Element at arr[1] : ", arr[1])

1
Element at arr[1] :  2


In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.ndim)

2


In [23]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2.ndim)

print("Element at arr[1, 2] : ", arr2[1, 2])

2
Element at arr[1, 2] :  6


In [35]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

print(arr3.ndim)

print("Element at arr[1, 1, 2] : ", arr3[1, 1, 2])

3
Element at arr[1, 1, 2] :  12


In [40]:
arr4 = np.array([7])

print(arr4.ndim)

1


In [41]:
arr5 = np.array(7)

print(arr5.ndim)

0


### 3. Shapes => shape()

In [37]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
# tuples(no.of 2D arrays, 1D arrays in each 2D array, elements in each 1D array)

arr3.shape

(2, 2, 3)

In [38]:
# Tells the total no.of 2D arrays

arr3.shape[0]

2

In [39]:
# Tells the total no. of 1d arrays in the 2D array

arr3.shape[1]

2

In [42]:
# Tells the totalno.of elements in a 1D array

arr3.shape[2]

3

### 4. Size

In [43]:
"""Total Number Of Elements In Array"""

'Total Number Of Elements In Array'

In [44]:
arr3.size

12

### 5. Bytes

In [45]:
arr3.nbytes

48

## NUMPY FUNCTIONS

### 1. np.arange()

###### Creates an array with values in a given range

In [46]:
arr = np.arange(100) # array of numbers from 0 - 99

In [47]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [48]:
arr2 = np.arange(20, 100) #array of numbers from 20 - 99

print(arr2)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [49]:
arr3 = np.arange(30, 100, 3) # array of numbers from 30 - 99 , with a step 3

print(arr3)

[30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99]


### 2. np.random.permutation

###### permutation => package inside random , it shuffles and rearranges all the values in a random order

In [50]:
arr = np.random.permutation(np.arange(20))

print(arr)

[ 4  3 16 11 17 15  1  7 12 14  6  2  5 10 18 19  8  9 13  0]


### 3. np.random.randint

###### randint => creates a random integer

In [54]:
arr1 = np.random.randint(20, 30)

print(arr1)

print("Type of : ",arr1, "is :: ", type(arr1))

22
Type of :  22 is ::  <class 'int'>


### 4. np.reshape

###### reorganizes an array to a desired dimensional array , for instance given an 1D array its can re-organize it to 2D etc

In [67]:
arr = np.arange(20).reshape(4, 5)

arr.shape

(4, 5)

In [68]:
arr1 = np.arange(30).reshape(2, 5, 3)

arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

### 5. random.rand()

###### generates random values between 0 and 1

In [55]:
arr = np.random.rand(10)

In [56]:
print(arr)

[0.71692392 0.11903513 0.21644226 0.00396578 0.79659497 0.936932
 0.90458555 0.4528642  0.21949975 0.54923983]


In [60]:
arr2 = np.random.rand(4,4)

print(arr2)

[[0.66905094 0.95359839 0.38131478 0.05305333]
 [0.1126191  0.7404039  0.69740742 0.32799482]
 [0.05906451 0.50115168 0.33225296 0.97809406]
 [0.53603376 0.95405808 0.12061062 0.854165  ]]


In [61]:
arr2.ndim

2

### np.random.randn()

###### generates real random values

In [57]:
arr = np.random.randn(10)

print(arr)

[-1.76846442  0.48134189 -0.9244977   0.74570358 -0.04151643 -0.56511331
  0.25754068 -0.91026435  1.15815475  0.57576345]


In [69]:
np.zeros?

In [70]:
np.ones?

## SLICING / INDEXING IN NUMPY

In [ ]:
"""Slicing Create A View Rather Than A Copy"""

###### arr[start:end:step]

###### arr[1:5] => 1 - 5 , 5 exclusive

###### arr[:5] => 0 - 5, 5 exclusive

###### arr[2:] => indexing from 2 till end , including last element

###### arr[::-1] => reverse an array

###### arr[::2] => start till end , after every 2 steps

### N/B :: SLICING in numpy REFERENCES THE ORIGINAL ARRAY => changes made to the sliced array also apply to the original array

In [71]:
arr = np.arange(100)

arr1 = arr[3:10]

print(arr1)

[3 4 5 6 7 8 9]


In [72]:
arr1[0] = -33

arr1

array([-33,   4,   5,   6,   7,   8,   9])

In [73]:
arr

array([  0,   1,   2, -33,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

### N/B:FOR THE EFFECT OF CHANGING A SLICED ARRAY NOT TO APPEAR IN ORIGINAL ARRAY => include the copy() function to make the copy of the new array which does not change the original array

In [75]:
arr = np.arange(50)

arr1  = arr[10:20].copy()

arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [76]:
arr1[6] = 77


In [77]:
arr1

array([10, 11, 12, 13, 14, 15, 77, 17, 18, 19])

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [79]:
arr[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [81]:
arr[::-3]

array([49, 46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4,  1])

In [82]:
arr[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [83]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])